"""models changes

Revision ID: 55309b9a11ee
Revises: a050976b70e3
Create Date: 2026-01-31 01:00:13.247323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55309b9a11ee'
down_revision: Union[str, Sequence[str], None] = 'a050976b70e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('books_user_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['created_by'], ['id'])
    op.drop_column('books', 'user_id')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('books', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_user_id_fkey'), 'books', 'users', ['user_id'], ['id'])
    op.drop_column('books', 'created_by')
    # ### end Alembic commands ###
