"""models changes

Revision ID: a5eafb2153f6
Revises: ea58c1b40684
Create Date: 2026-01-31 00:46:47.466123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5eafb2153f6'
down_revision: Union[str, Sequence[str], None] = 'ea58c1b40684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('books_created_by_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'])
    op.drop_column('books', 'created_by')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('books', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_created_by_fkey'), 'books', 'users', ['created_by'], ['id'])
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
