"""add user_id to books

Revision ID: cb6cbd27f5d5
Revises: 4c3eb6b0e89d
Create Date: 2026-01-30 01:23:09.865184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb6cbd27f5d5'
down_revision: Union[str, Sequence[str], None] = '4c3eb6b0e89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('created_by', sa.UUID(), nullable=True, foreign_key='users.id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'created_by')
    # ### end Alembic commands ###
